### ISSUE TITLE
cannot install mysql-python

### ISSUE THREAD

**Issue by pzjc** [CornellProjects/hlthpal#15]
cannot install mysql-python when I directly run "pip install -r requirements.txt"
give me this error
"Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/df/2ndtjwkx5d3gj61kh0d91m040000gn/T/pip-build-MqI9Cd/mysql-python/
"

**Comment by nishkumar** [comment]
Yes . This was because the pip freeze command was run before  mysql-python was installed.

**Comment by nishkumar** [comment]
Add to requirements.txt if required. Or just use sqlite DB.
