### ISSUE TITLE
How do we handle doctor registration in the database?

### ISSUE THREAD

**Issue by nishkumar** [CornellProjects/hlthpal#4]
The patient register api requires a doctor to be associated with every patient.  Is this a required field or can we register a patient without a doctor.  How do we update the doctor info in the database?

**Comment by lbarros00** [comment]
Doctor registration can be found under url:  api/doctor
Each doctor is associated with an Entity so an entity has to be created: api/entity
before a doctor can register

**Comment by nishkumar** [comment]
Doctor registration to be done by site admin. This will be don either via Dashboard or Django Admin.
