### ISSUE TITLE
User register api, Doctor field 

### ISSUE THREAD

**Issue by nishkumar** [CornellProjects/hlthpal#8]
How do we handle the doctor field in  User Register api?

**Comment by lbarros00** [comment]
For now, doctor field in Patient model for testing purposes we will leave it as a CharField

**Comment by nishkumar** [comment]
If we map to doctor field  we need an api to get all doctors so that id can be stored in doctor field.

**Comment by lbarros00** [comment]
That's the plan once a doctor can register through Django Admin or the Dashboard website.

**Comment by nishkumar** [comment]
Handle in Django or dashboard.
